// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ_qZ4pQFok5AoU7OQATkthBFNVlCgqiI',
    appId: '1:904959608492:web:69d1f41cbf2cf6850b8109',
    messagingSenderId: '904959608492',
    projectId: 'logindemo-9ce1a',
    authDomain: 'logindemo-9ce1a.firebaseapp.com',
    storageBucket: 'logindemo-9ce1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMOlQlN4Fuaw1MWdNeyfI6d5aK9akCPwI',
    appId: '1:904959608492:android:9fd8863444860a1c0b8109',
    messagingSenderId: '904959608492',
    projectId: 'logindemo-9ce1a',
    storageBucket: 'logindemo-9ce1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASqQK4XpetWVI9JAotBheIZefTBctePy4',
    appId: '1:904959608492:ios:4cf87195f0c3baf70b8109',
    messagingSenderId: '904959608492',
    projectId: 'logindemo-9ce1a',
    storageBucket: 'logindemo-9ce1a.appspot.com',
    iosClientId: '904959608492-qialpsreldiqngfeqmkjfv205tnso1e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASqQK4XpetWVI9JAotBheIZefTBctePy4',
    appId: '1:904959608492:ios:9f6abae197254a850b8109',
    messagingSenderId: '904959608492',
    projectId: 'logindemo-9ce1a',
    storageBucket: 'logindemo-9ce1a.appspot.com',
    iosClientId: '904959608492-4mclvalpjbi0lajlgg63u9nljvh446jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
